In [4]:
import findspark
findspark.init()

from pyspark.sql.session import SparkSession
from pyspark.sql.functions import col
from pyspark.sql import SQLContext

In [8]:
spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.some.config.option", "some-value") \
    .getOrCreate()

df = spark.read.option(
    "multiline", "true"
).option(
    "quote", '"'
).option(
    "escape", '"'
).csv(
    "./../datasets/netflix_reviews.csv", 
    header=True, 
    sep=","
)

In [9]:
cols = ["userName", "score"]

In [10]:
print(df.select(*cols).filter(df.score.isNotNull()).orderBy(df.score.desc()).show())

+--------------------+-----+
|            userName|score|
+--------------------+-----+
|         Deb Perkins|    5|
|Ninanona Cervante...|    5|
|         Lolis Ramos|    5|
|           Mahi Zaib|    5|
|       Esther Elijah|    5|
|   ARGHYADEEP BISWAS|    5|
|     Danial Abellera|    5|
|     Arashvir bhatti|    5|
|     Jonathan Kaplan|    5|
|        BURAK PRINCE|    5|
|        Maria Morfin|    5|
|      melody sikeezi|    5|
|          Iᴀɴ ᴡɪʟsᴏɴ|    5|
|     Natalia Stadnic|    5|
|             Hey Hey|    5|
|   Hyderali Hyderali|    5|
|  Ritesh kumar Singh|    5|
|           Abdou Aid|    5|
|        Gunja_-Anime|    5|
|         Mel Carpena|    5|
+--------------------+-----+
only showing top 20 rows

None

In [11]:
df.dtypes

[('reviewId', 'string'),
 ('userName', 'string'),
 ('content', 'string'),
 ('score', 'string'),
 ('thumbsUpCount', 'string'),
 ('reviewCreatedVersion', 'string'),
 ('at', 'string'),
 ('appVersion', 'string')]

In [12]:
fd = df.select(*cols).filter(df.score.isNotNull())
fd.sort(col("score")).collect()

fd.collect()

[Row(userName='konadu Emmanuel', score='5'),
 Row(userName='xari malik', score='1'),
 Row(userName='Dexter Clarke', score='1'),
 Row(userName='Abdou Aid', score='5'),
 Row(userName='ARGHYADEEP BISWAS', score='5'),
 Row(userName='Ray F', score='5'),
 Row(userName='Arashvir bhatti', score='5'),
 Row(userName='Mel Carpena', score='5'),
 Row(userName='Sadaf Khan', score='1'),
 Row(userName='Kevin Guerra', score='1'),
 Row(userName='BURAK PRINCE', score='5'),
 Row(userName='Sindri Gríms', score='1'),
 Row(userName='Favour Ukwuoma', score='1'),
 Row(userName='Adolfo Aviles', score='1'),
 Row(userName='Dale Sanford', score='4'),
 Row(userName='Karl Harvey', score='5'),
 Row(userName='Holly Hendershot', score='4'),
 Row(userName='Lusi Rahmawati', score='1'),
 Row(userName='melody sikeezi', score='5'),
 Row(userName='Paul Aberee', score='5'),
 Row(userName='Natalia Stadnic', score='5'),
 Row(userName='King Jay', score='1'),
 Row(userName='Deb Perkins', score='5'),
 Row(userName='Lilly Meyer', score='4'),
 Row(userName='Simon Walters', score='1'),
 Row(userName='Hyderali Hyderali', score='5'),
 Row(userName='Kung Fu Scooby', score='1'),
 Row(userName='BK (BK)', score='1'),
 Row(userName='nald fernandez', score='5'),
 Row(userName='Davy Cox', score='1'),
 Row(userName='Harshad Amrute (DeXTeR)', score='1'),
 Row(userName='Malindi Simelane', score='1'),
 Row(userName='Molly (Mollu)', score='1'),
 Row(userName='Joe Gerien Phongpheera.K', score='1'),
 Row(userName='Lolis Ramos', score='5'),
 Row(userName='Christ Khuhly', score='1'),
 Row(userName='Esther Elijah', score='5'),
 Row(userName='Danial Abellera', score='5'),
 Row(userName='Jonathan Kaplan', score='5'),
 Row(userName='Chey star', score='4'),
 Row(userName='Maitri Desai', score='2'),
 Row(userName='Sayn Yt', score='1'),
 Row(userName='Rahim Khan', score='1'),
 Row(userName='Maria Morfin', score='5'),
 Row(userName='Emitra Jaipur', score='1'),
 Row(userName='Iᴀɴ ᴡɪʟsᴏɴ', score='5'),
 Row(userName='Uchenna Ugokwe', score='1'),
 Row(userName='Hey Hey', score='5'),
 Row(userName='Akheelah Sithole', score='1'),
 Row(userName='meera joshi', score='1'),
 Row(userName='Ajay Yadav', score='1'),
 Row(userName='Ireoluwatomiwa Salu', score='2'),
 Row(userName='Ritesh kumar Singh', score='5'),
 Row(userName='Chitra Bhaskar', score='1'),
 Row(userName='Gunja_-Anime', score='5'),
 Row(userName='fitazrai', score='1'),
 Row(userName='Silas Trigg', score='5'),
 Row(userName='Olaoye Damilola', score='5'),
 Row(userName='Mod Jha', score='5'),
 Row(userName='Noor Khan', score='1'),
 Row(userName='ABHISHEK KUMAR', score='1'),
 Row(userName='Mahi Zaib', score='5'),
 Row(userName='Navika Sonwal', score='1'),
 Row(userName='Ninanona Cervantes Lina', score='5'),
 Row(userName='Favor Ekpe', score='3'),
 Row(userName='Mohd Kehef', score='1'),
 Row(userName='Sebastian ramos', score='5'),
 Row(userName='Israel Maldonado', score='1'),
 Row(userName='Varinder Singh', score='1'),
 Row(userName='Shailesh Mohbarsa', score='1'),
 Row(userName='Spiderman Parkour', score='1'),
 Row(userName='Waqar Ahmad', score='5'),
 Row(userName='Aman K', score='1'),
 Row(userName='santosh dutta', score='1'),
 Row(userName='nat bug', score='1'),
 Row(userName='Kamaraj Ramasamy', score='5'),
 Row(userName='suryakiran p', score='1'),
 Row(userName='Jared Mchugh', score='2'),
 Row(userName='Rinsureka Okama', score='5'),
 Row(userName='Kishor Kudale', score='1'),
 Row(userName='Tmr Zlwo', score='5'),
 Row(userName='Hanshika Soni', score='5'),
 Row(userName='Galia Angelin', score='5'),
 Row(userName='Msqtpie4u', score='3'),
 Row(userName='Sajid Ali', score='5'),
 Row(userName='Saira Sairaijs', score='5'),
 Row(userName='Umar Mustafai', score='5'),
 Row(userName='Delilah Godinho', score='5'),
 Row(userName='Hermien Kemp', score='5'),
 Row(userName='selena leitch', score='5'),
 Row(userName='Lilly Anna', score='4'),
 Row(userName='Kim Jones', score='1'),
 Row(userName='Shivani Pandey', score='1'),
 Row(userName='Dexter Capioc', score='1'),
 Row(userName='Dakota', score='4'),
 Row(userName='Karl Morris', score='1'),
 Row(userName='Glyn Rogers', score='1'),
 Row(userName='Jabulani Hlongwane', score='5'),
 Row(userName='Naveed ahmed', score='1'),
 Row(userName='So Hail', score='1'),
 Row(userName='Sahil Chauhan', score='4'),
 Row(userName='Irum adnan', score='3'),
 Row(userName='Habia Jaan', score='3'),
 Row(userName='Ojing Tamut', score='5'),
 Row(userName='edward wy', score='5'),
 Row(userName='Joseph Kasemuana', score='2'),
 Row(userName='Moonbeam Rhe', score='5'),
 Row(userName='Malak Al saaegh', score='1'),
 Row(userName='Tebogo Kgobokoe', score='5'),
 Row(userName='Rico Bernasor', score='5'),
 Row(userName='Nils Mueller', score='1'),
 Row(userName='M Bilal', score='5'),
 Row(userName='Shiela Josol', score='1'),
 Row(userName='AMINA BALA', score='2'),
 Row(userName='Ivan L', score='1'),
 Row(userName='Balachandran Adukattil', score='5'),
 Row(userName='Azat', score='1'),
 Row(userName='Munyaradzi Gonyora', score='5'),
 Row(userName='Rakesh Varma 7', score='5'),
 Row(userName='Amenah Adil', score='1'),
 Row(userName='Nagatharisini Sukumaran', score='3'),
 Row(userName='Tia Charles', score='3'),
 Row(userName='Snenhlanhla Zondi', score='5'),
 Row(userName='Manuel Lobato', score='1'),
 Row(userName='Suzanne Careless', score='5'),
 Row(userName='Charlie Clare', score='4'),
 Row(userName='Ali', score='1'),
 Row(userName='Mensur Akrem', score='5'),
 Row(userName='جمعه الحمادي', score='5'),
 Row(userName='ara jasmine', score='1'),
 Row(userName='Mohamed Noman', score='5'),
 Row(userName='Ghita Malinetescu', score='5'),
 Row(userName='Sikandar Ibrahim', score='5'),
 Row(userName='Sadat Abdul-Rasheed', score='1'),
 Row(userName='Silver', score='2'),
 Row(userName='Rucha Barve', score='1'),
 Row(userName='Christopher “Austin” Kelsey', score='2'),
 Row(userName='Who Cares', score='1'),
 Row(userName='Fardin Islam', score='1'),
 Row(userName='Gaggu Mallhi', score='4'),
 Row(userName='ajay sharma', score='1'),
 Row(userName='zain shahbaz', score='4'),
 Row(userName='Ganagalla Thotayya', score='1'),
 Row(userName='Gokul Subha,kayal,ammu', score='2'),
 Row(userName='Pearl Fernandes', score='5'),
 Row(userName='Dharrshan', score='1'),
 Row(userName='E A Sivaraman', score='5'),
 Row(userName='Toffi Nini', score='1'),
 Row(userName='Paran Lekharu', score='1'),
 Row(userName='Fermín Alejandra', score='1'),
 Row(userName='Payel Chakraborty', score='1'),
 Row(userName='Naseem Sher Jan', score='1'),
 Row(userName='Padmini AK', score='5'),
 Row(userName='Alpha Thongpitak', score='5'),
 Row(userName='Puneet Sharma', score='1'),
 Row(userName='Jerry Thomas', score='1'),
 Row(userName='Mohammad Kamran', score='5'),
 Row(userName='Trez Pinkney', score='2'),
 Row(userName='GOBENATHEN THIAGARAJAN', score='1'),
 Row(userName='Garry Mayo', score='5'),
 Row(userName='Kj Rouse', score='1'),
 Row(userName='Chad Taylor', score='1'),
 Row(userName='Nancy Carrière', score='2'),
 Row(userName='Alexander Leutwiler', score='1'),
 Row(userName='Sachika Kylia', score='1'),
 Row(userName='Carl Furfaro', score='1'),
 Row(userName='shivani gupta', score='1'),
 Row(userName='Ethan Kayl', score='5'),
 Row(userName='Johnny', score='5'),
 Row(userName='Nagendra Dharwar', score='5'),
 Row(userName='Sathish Bandari', score='5'),
 Row(userName='Nandita Rabha', score='5'),
 Row(userName='Kathy Beech', score='5'),
 Row(userName='Matthew Reyes', score='2'),
 Row(userName='Miller Elizabeth', score='5'),
 Row(userName='Udoka Chukwudike', score='4'),
 Row(userName='George Ward', score='1'),
 Row(userName='Okoro Ruth Oluchi', score='1'),
 Row(userName='Stacey Harrison', score='1'),
 Row(userName='Nill Anjo Quiao', score='2'),
 Row(userName='Saim Prince', score='5'),
 Row(userName='Khan Owais', score='1'),
 Row(userName='Čhoedon Thi', score='3'),
 Row(userName='Corentin Muheim', score='1'),
 Row(userName='sandeep singh', score='1'),
 Row(userName='Mian Ahsan', score='5'),
 Row(userName='Hemmigumm', score='1'),
 Row(userName='Mujahid Gani', score='1'),
 Row(userName='Djinn', score='5'),
 Row(userName='Mohammed AlQudah', score='4'),
 Row(userName='E L', score='3'),
 Row(userName='ezza butt', score='3'),
 Row(userName='A F', score='3'),
 Row(userName='Jagmeet Singh', score='5'),
 Row(userName='ife ojo', score='1'),
 Row(userName='Suyee Tong-Lee', score='1'),
 Row(userName='Gloria Castaneda', score='5'),
 Row(userName='Dusenburg Goodwin', score='1'),
 Row(userName='lauren Bee', score='1'),
 Row(userName='Esther Maghenda', score='1'),
 Row(userName='Ramin Tabnak', score='1'),
 Row(userName='King zkria Khan', score='5'),
 Row(userName='Alan Baum', score='5'),
 Row(userName='Prem Pal', score='5'),
 Row(userName='Sebastian NG', score='3'),
 Row(userName='Janet Moraa', score='5'),
 Row(userName='Hafizur Rahman', score='1'),
 Row(userName='Julian Foster', score='1'),
 Row(userName='Ramen Eater', score='1'),
 Row(userName='Maria Mubarak', score='5'),
 Row(userName='Abhishek Bhure', score='1'),
 Row(userName='John “Spect”', score='1'),
 Row(userName='Josh Manke', score='1'),
 Row(userName='Memmeng Ngakane', score='5'),
 Row(userName='Isra Gashi', score='5'),
 Row(userName='yogesh sheelwant', score='4'),
 Row(userName='sic sock rock', score='4'),
 Row(userName='Emmanuel Garcia', score='1'),
 Row(userName='Hassan Roba', score='5'),
 Row(userName='ventus kh', score='1'),
 Row(userName='najab najab', score='5'),
 Row(userName='Doug Mitchell', score='5'),
 Row(userName='Divine Cahigos', score='5'),
 Row(userName='Michael Aidoo', score='5'),
 Row(userName='Denver Minnie', score='1'),
 Row(userName='Deepak Sen', score='1'),
 Row(userName='Rony Muza', score='5'),
 Row(userName='Navnit RAJ', score='1'),
 Row(userName='satyakam ItoI', score='1'),
 Row(userName='Ankan Dasgupta', score='1'),
 Row(userName='Nitin Nomadic', score='1'),
 Row(userName='Ariyan Nisaniya', score='1'),
 Row(userName='shailesh patel', score='5'),
 Row(userName='Navin Gupta', score='1'),
 Row(userName='ADARSH KUMAR', score='5'),
 Row(userName='Liam Arendt', score='1'),
 Row(userName='Nipa Patel', score='1'),
 Row(userName='Manas Gupta', score='1'),
 Row(userName='Jeff Kline', score='5'),
 Row(userName='Anuradha Parakkat', score='5'),
 Row(userName='Mohammad Jabali', score='1'),
 Row(userName='Olamilekan Timziano', score='5'),
 Row(userName='chandu chandana', score='1'),
 Row(userName='Daniel Milford', score='5'),
 Row(userName='pawara sonu', score='1'),
 Row(userName='Kaushik Ghosh', score='1'),
 Row(userName='Iko Chan', score='1'),
 Row(userName='Erina Iqbal', score='1'),
 Row(userName='fabiola borbon', score='3'),
 Row(userName='kitagz12345', score='1'),
 Row(userName='Sharib Ansari', score='3'),
 Row(userName='Everrrtt Hogue', score='1'),
 Row(userName='Wasswa Hamidu', score='5'),
 Row(userName='WAQAS AFZAL', score='1'),
 Row(userName='Xhavit Ismaili', score='1'),
 Row(userName='rajeshkumar rajeshkumar', score='1'),
 Row(userName='Vijay Shiware', score='1'),
 Row(userName='Jill Imperial', score='5'),
 Row(userName='Subhrangshu Singha', score='1'),
 Row(userName='Juan Garcia', score='5'),
 Row(userName='Bramono Adi', score='2'),
 Row(userName='Demir R', score='1'),
 Row(userName='Anthony Jackson', score='1'),
 Row(userName='Aashir Khan', score='3'),
 Row(userName='Cindy', score='5'),
 Row(userName='harry brown', score='5'),
 Row(userName='Kent Angelo', score='1'),
 Row(userName='H F', score='2'),
 Row(userName='Nkuba Nkuba', score='5'),
 Row(userName='Robert Anthony', score='5'),
 Row(userName='Mukamwiza Olive', score='5'),
 Row(userName='Marvel Dwi Nugraha', score='5'),
 Row(userName='OMAR omarJaji', score='5'),
 Row(userName='Iqra Waheed', score='5'),
 Row(userName='rupali chatterjee', score='1'),
 Row(userName='Lexiconis Lumen', score='5'),
 Row(userName='Komolafe Success', score='5'),
 Row(userName='Aastik Phadnis', score='3'),
 Row(userName='gintoki [Räm]', score='1'),
 Row(userName='George Angelogiannos', score='5'),
 Row(userName='LB Espiritu', score='5'),
 Row(userName='Muhammad Hassan', score='5'),
 Row(userName='Ignatius Hipangelwa', score='5'),
 Row(userName='Sahebrav Shelar', score='5'),
 Row(userName='Ola Majed', score='1'),
 Row(userName='kaviyasree s', score='2'),
 Row(userName='Shadrack Motsamai', score='1'),
 Row(userName='Jabu Tembe', score='1'),
 Row(userName='Chloe Young', score='5'),
 Row(userName='Jacob Fatah', score='5'),
 Row(userName='Cos B', score='3'),
 Row(userName='acharya lalit', score='5'),
 Row(userName='Eric Smith', score='1'),
 Row(userName='Raksan Reks', score='1'),
 Row(userName='PRANAY YADAV KINGS', score='5'),
 Row(userName='Demon *', score='5'),
 Row(userName='Shobhana Narayanan', score='5'),
 Row(userName='Roxanne', score='1'),
 Row(userName='Gourav Jatav', score='5'),
 Row(userName='Mark Okestone', score='1'),
 Row(userName='lukman hakim', score='1'),
 Row(userName='Levin', score='5'),
 Row(userName='Bogdan Oscar', score='5'),
 Row(userName='Adam Michael', score='5'),
 Row(userName='Lauritta Boniface', score='5'),
 Row(userName='Ansu Agarwal', score='1'),
 Row(userName='jeffrey nazario', score='1'),
 Row(userName='Krishna Sharma', score='5'),
 Row(userName='DANY RICHARDS', score='5'),
 Row(userName='Rose Zimik', score='1'),
 Row(userName='kvallari Kumar', score='5'),
 Row(userName='MG BOSS BHAI', score='1'),
 Row(userName='Charles R Harris Jr', score='1'),
 Row(userName='Bryan Fong', score='1'),
 Row(userName='Cur Spar', score='1'),
 Row(userName='Pushpa Timilsena', score='5'),
 Row(userName='Angelo Oliveros', score='2'),
 Row(userName='Divya Patil', score='5'),
 Row(userName='Marie Ronalde Merisme', score='5'),
 Row(userName='Waqas Mughal', score='5'),
 Row(userName='Athipatla Prem', score='1'),
 Row(userName='Bethany Barnes', score='1'),
 Row(userName='michael thompson', score='5'),
 Row(userName='Omar Emera', score='1'),
 Row(userName='X Xxxx', score='3'),
 Row(userName='Matthew Wagner', score='1'),
 Row(userName='Richard G', score='1'),
 Row(userName='Patel Shrikunj', score='1'),
 Row(userName='J i n', score='1'),
 Row(userName='James Lafon', score='5'),
 Row(userName='TalalioisKewl', score='1'),
 Row(userName='Cory Kent', score='1'),
 Row(userName='Savanna Max', score='2'),
 Row(userName='Erika Thomas', score='1'),
 Row(userName='No One Is this', score='2'),
 Row(userName='Abdulrahman AlJbouri', score='1'),
 Row(userName='Sampa Sengupta', score='1'),
 Row(userName='uzaif maqbool', score='5'),
 Row(userName='Maahir Vishakha Gada Gala', score='1'),
 Row(userName='Dee Kirk', score='3'),
 Row(userName='Ghelian Lei Peralta', score='1'),
 Row(userName='Josh Silverman', score='1'),
 Row(userName='Jose Agustin', score='1'),
 Row(userName='Ashley Campbell', score='1'),
 Row(userName='Saint Ryan', score='1'),
 Row(userName='Vivian Lusay', score='5'),
 Row(userName='Stirech', score='5'),
 Row(userName='Lylah Joly', score='3'),
 Row(userName='Elixir Weir', score='5'),
 Row(userName='Gad Win', score='5'),
 Row(userName='Luis Rodríguez', score='4'),
 Row(userName='shailesh patel', score='5'),
 Row(userName='Navin Gupta', score='1'),
 Row(userName='ADARSH KUMAR', score='5'),
 Row(userName='Liam Arendt', score='1'),
 Row(userName='Nipa Patel', score='1'),
 Row(userName='Manas Gupta', score='1'),
 Row(userName='Jeff Kline', score='5'),
 Row(userName='Anuradha Parakkat', score='5'),
 Row(userName='Mohammad Jabali', score='1'),
 Row(userName='Olamilekan Timziano', score='5'),
 Row(userName='chandu chandana', score='1'),
 Row(userName='Daniel Milford', score='5'),
 Row(userName='pawara sonu', score='1'),
 Row(userName='Kaushik Ghosh', score='1'),
 Row(userName='Iko Chan', score='1'),
 Row(userName='Erina Iqbal', score='1'),
 Row(userName='fabiola borbon', score='3'),
 Row(userName='kitagz12345', score='1'),
 Row(userName='Sharib Ansari', score='3'),
 Row(userName='Everrrtt Hogue', score='1'),
 Row(userName='Wasswa Hamidu', score='5'),
 Row(userName='WAQAS AFZAL', score='1'),
 Row(userName='Xhavit Ismaili', score='1'),
 Row(userName='rajeshkumar rajeshkumar', score='1'),
 Row(userName='Vijay Shiware', score='1'),
 Row(userName='Jill Imperial', score='5'),
 Row(userName='Subhrangshu Singha', score='1'),
 Row(userName='Juan Garcia', score='5'),
 Row(userName='Bramono Adi', score='2'),
 Row(userName='Demir R', score='1'),
 Row(userName='Anthony Jackson', score='1'),
 Row(userName='Aashir Khan', score='3'),
 Row(userName='Cindy', score='5'),
 Row(userName='harry brown', score='5'),
 Row(userName='Kent Angelo', score='1'),
 Row(userName='H F', score='2'),
 Row(userName='Nkuba Nkuba', score='5'),
 Row(userName='Robert Anthony', score='5'),
 Row(userName='Mukamwiza Olive', score='5'),
 Row(userName='Marvel Dwi Nugraha', score='5'),
 Row(userName='OMAR omarJaji', score='5'),
 Row(userName='Iqra Waheed', score='5'),
 Row(userName='rupali chatterjee', score='1'),
 Row(userName='Lexiconis Lumen', score='5'),
 Row(userName='Komolafe Success', score='5'),
 Row(userName='Aastik Phadnis', score='3'),
 Row(userName='gintoki [Räm]', score='1'),
 Row(userName='George Angelogiannos', score='5'),
 Row(userName='LB Espiritu', score='5'),
 Row(userName='Muhammad Hassan', score='5'),
 Row(userName='Ignatius Hipangelwa', score='5'),
 Row(userName='Sahebrav Shelar', score='5'),
 Row(userName='Ola Majed', score='1'),
 Row(userName='kaviyasree s', score='2'),
 Row(userName='Shadrack Motsamai', score='1'),
 Row(userName='Jabu Tembe', score='1'),
 Row(userName='Chloe Young', score='5'),
 Row(userName='Jacob Fatah', score='5'),
 Row(userName='Cos B', score='3'),
 Row(userName='acharya lalit', score='5'),
 Row(userName='Eric Smith', score='1'),
 Row(userName='Raksan Reks', score='1'),
 Row(userName='PRANAY YADAV KINGS', score='5'),
 Row(userName='Demon *', score='5'),
 Row(userName='Shobhana Narayanan', score='5'),
 Row(userName='Roxanne', score='1'),
 Row(userName='Gourav Jatav', score='5'),
 Row(userName='Mark Okestone', score='1'),
 Row(userName='lukman hakim', score='1'),
 Row(userName='Levin', score='5'),
 Row(userName='Bogdan Oscar', score='5'),
 Row(userName='Adam Michael', score='5'),
 Row(userName='Lauritta Boniface', score='5'),
 Row(userName='Ansu Agarwal', score='1'),
 Row(userName='jeffrey nazario', score='1'),
 Row(userName='Krishna Sharma', score='5'),
 Row(userName='DANY RICHARDS', score='5'),
 Row(userName='Rose Zimik', score='1'),
 Row(userName='kvallari Kumar', score='5'),
 Row(userName='MG BOSS BHAI', score='1'),
 Row(userName='Charles R Harris Jr', score='1'),
 Row(userName='Bryan Fong', score='1'),
 Row(userName='Cur Spar', score='1'),
 Row(userName='Pushpa Timilsena', score='5'),
 Row(userName='Angelo Oliveros', score='2'),
 Row(userName='Divya Patil', score='5'),
 Row(userName='Marie Ronalde Merisme', score='5'),
 Row(userName='Waqas Mughal', score='5'),
 Row(userName='Athipatla Prem', score='1'),
 Row(userName='Bethany Barnes', score='1'),
 Row(userName='michael thompson', score='5'),
 Row(userName='Omar Emera', score='1'),
 Row(userName='X Xxxx', score='3'),
 Row(userName='Matthew Wagner', score='1'),
 Row(userName='Richard G', score='1'),
 Row(userName='Patel Shrikunj', score='1'),
 Row(userName='J i n', score='1'),
 Row(userName='James Lafon', score='5'),
 Row(userName='TalalioisKewl', score='1'),
 Row(userName='Cory Kent', score='1'),
 Row(userName='Savanna Max', score='2'),
 Row(userName='Erika Thomas', score='1'),
 Row(userName='No One Is this', score='2'),
 Row(userName='Abdulrahman AlJbouri', score='1'),
 Row(userName='Sampa Sengupta', score='1'),
 Row(userName='uzaif maqbool', score='5'),
 Row(userName='Maahir Vishakha Gada Gala', score='1'),
 Row(userName='Dee Kirk', score='3'),
 Row(userName='Ghelian Lei Peralta', score='1'),
 Row(userName='Josh Silverman', score='1'),
 Row(userName='Jose Agustin', score='1'),
 Row(userName='Ashley Campbell', score='1'),
 Row(userName='Saint Ryan', score='1'),
 Row(userName='Vivian Lusay', score='5'),
 Row(userName='Stirech', score='5'),
 Row(userName='Lylah Joly', score='3'),
 Row(userName='Elixir Weir', score='5'),
 Row(userName='Gad Win', score='5'),